### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by PS-AI** [geblanco/mc_transformers#95]
* mc_transformers version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Hi,
I am new to NLP. I am trying to learn to code a multiple choice question generator. I came across this repository. Thank you for the package. Can you give an example of its usage - i.e. how can we fulfill a business use case of writing code that will generate multiple choice questions from a given text using the mc_transformers package.

```. 
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by geblanco** [comment]
This package can help you to train a generator model, but you'd have to program the necessary steps to use that model to generate text.
